version: "3"
services:
  database:
    image: postgres:11-alpine
    environment:
       - POSTGRES_DB=tech
       - POSTGRES_USER=tech_user
       - POSTGRES_PASSWORD=tech_pass
    ports:
      - "5433:5432"
    volumes:
      - db-data-tech:/var/lib/postgresql/data

volumes:
  db-data-tech:
